OO PLACEMENT DESCRIPTION + EXERCISES
green-fox-academy/http-info-syllabus pull request #1
Opened 2019-10-15 22:35 UTC by Gilthanas122

proof reading required

2019-10-16 05:55 UTC, rviktor87 requested changes
Fixing a lot of typo

2019-10-16 05:55 UTC, rviktor87 commented on OOPlacement.md
> +* Ha bizonytalan vagy, lójj fólé inkább egy feladattal, mint alá. Ott lesznek a mentoraid es a csoporttársaid, hogy segítsenek.
```suggestion
* Ha bizonytalan vagy, lőjj fölé inkább egy feladattal, mint alá. Ott lesznek a mentoraid és a csoporttársaid, hogy segítsenek.
```

2019-10-16 05:55 UTC, rviktor87 commented on OOPlacement.md
> +*   Töltsd fel 10-10 fiú és lány névvel szöveg típusként(_String Object_). Nevezd el 10bé-nek.
A változó neve legyen 10b? Kezdődhet számmal egy változó?

2019-10-16 05:55 UTC, rviktor87 commented on OOPlacement.md
> +*   Írj egy függvényt és nézd meg, hogy kinek a neve tartalmazza a 'p' betút.
```suggestion
*   Írj egy függvényt és nézd meg, hogy kinek a neve tartalmazza a 'p' betűt.
```

2019-10-16 05:55 UTC, rviktor87 commented on OOPlacement.md
> +*   Ha van kozottuk olyan, akinek a neve nem palindróma, akkor fejezd ki enyhe rosszallásodat es töröld minden második diák nevét a listáról
```suggestion
*   Ha van közöttük olyan, akinek a neve nem palindróma, akkor fejezd ki enyhe rosszallásodat es töröld minden második diák nevét a listáról
```

2019-10-16 05:55 UTC, rviktor87 commented on OOPlacement.md
> +*   Dolgozatírás. A dolgozat pontjait a nevük betúiből összeálló karakterek karakter)_Character value_) értékei adják.
```suggestion
*   Dolgozatírás. A dolgozat pontjait a nevük betűiből összeálló karakterek karakter (_Character value_) értékei adják. 
```

2019-10-16 05:55 UTC, rviktor87 commented on OOPlacement.md
> +*   Az így kapott értéket rendeld hozza egy asszociatív tömbben (_Map_) a statikus tömbszerkezet elemeihez, azaz a diákokhoz rendeld hozzá a pontokat.
```suggestion
*   Az így kapott értéket rendeld hozzá egy asszociatív tömbben (_Map_) a statikus tömbszerkezet elemeihez, azaz a diákokhoz rendeld hozzá a pontokat.
```

2019-10-16 05:55 UTC, rviktor87 commented on OOPlacement.md
> +*   Írasd bele a neveiket egy osztálynaplöba: hozz létre egy fájlt, amelyben a diákok es a jegyeik szerepelnek egymás mellett egy sorban: 1. Olivia, Pontszám 92
```suggestion
*   Írasd bele a neveiket egy osztálynaplóba: hozz létre egy fájlt, amelyben a diákok es a jegyeik szerepelnek egymás mellett egy sorban: 1. Olivia, Pontszám 92
```

2019-10-16 05:55 UTC, rviktor87 commented on OOPlacement.md
> +*   Hozz létre egy Student osztályt(_ ha létrehozunk egyet, akkor Object, egyebként Class_)  egy külön fájlban
```suggestion
*   Hozz létre egy Student osztályt (_ ha létrehozunk egyet, akkor Object, egyébként Class_)  egy külön fájlban
```

2019-10-16 05:55 UTC, rviktor87 commented on OOPlacement.md
> +*   Ez rendelkezzen a következő értékmezókkel, jellemzőkkel(_field variable_): name, points, isItPalindrome
```suggestion
*   Ez rendelkezzen a következő értékmezőkkel, jellemzőkkel(_field variable_): name, points, isItPalindrome
```

2019-10-16 05:55 UTC, rviktor87 commented on OOPlacement.md
> +*   Hozzál létre két listát )_List_), amely Student elemeket tud tárolni
```suggestion
*   Hozz létre két listát (_List_), amely Student elemeket tud tárolni
```

2019-10-16 05:55 UTC, rviktor87 commented on OOPlacement.md
> +*   Töltsd fel a file-ból a két listát, az ottani adatokkal hozzál létre diákokat és oszd így ketté őket
```suggestion
*   Töltsd fel a file-ból a két listát, az ottani adatokkal hozz létre diákokat és oszd így ketté őket
```

2019-10-16 05:55 UTC, rviktor87 commented on OOPlacement.md
> +*   Hasonlitsd ossze a ket lista tagjainak pontszámát egymással. Írasd ki az öt legsikeresebb diákot ezen összehasonlítás eredményeként
```suggestion
*   Hasonlitsd össze a két lista tagjainak pontszámát egymással. Írasd ki az öt legsikeresebb diákot ezen összehasonlítás eredményeként
```

2019-10-17 06:25 UTC, Gilthanas122 commented on OOPlacement.md
> +*   Töltsd fel 10-10 fiú és lány névvel szöveg típusként(_String Object_). Nevezd el 10bé-nek.
Igazad van, nem gondoltam erre!

2019-10-17 15:57 UTC, EggDice approved these changes

2019-10-17 15:58 UTC, merged