Suggestion for translation
green-fox-academy/http-info-syllabus pull request #3
Opened 2019-10-18 19:02 UTC by gabor-wermer-epam

2019-10-19 17:20 UTC, rviktor87 requested changes
Az ékezetes method és változó neveket jobb kerülni.

2019-10-31 11:37 UTC, markkovari commented
Na kerem holgyeim es uraim, azert itt vannak erdekes dolgok. Udv @gabor-wermer-epam  <3

2020-10-16 18:40 UTC, evasimonyi commented
@gabor-wermer-epam @markkovari @rviktor87 can I close this PR?
or should I fix this?

2020-10-17 09:18 UTC, rviktor87 commented
I closed this one. I won't use hungarian variable names...

2020-10-17 09:18 UTC, closed without merging